'use strict';

var R6MLangTerms = (function(undefined) {
  var terms = {},
    name = 'pc',
    loadedLang = 'pc',
    loadedDirection = 'LTR',
    translations = {},
    callTerms = {
      general: {
        pageTitle: 'R6Calls.com - {mapName}',
        pageTitleSelectMap: 'R6Calls.com - Select a map',
        pageTitleStart: 'R6Calls.com',
        cameraViewCaption: '{floorName} Camera View',
        shortcutTip: 'Shortcut: {shortcut}',
        menu: 'Menu',
        about: 'About',
        languageHeader: 'Language',
        optionsHeader: 'Options',
        labelLosOpacity: 'Camera line-of-sight opacity',
        linkAbout: 'about/about.html',
        labelPercent: '{int}%', // according to: (0.12).toLocaleString('en', { style: 'percent' });
        labelLosDefault: '(Default)',
        labelLos105: '(Huh?)',
        labelLos110: '(Ludicrous!)',
        labelRoomLabelStyle: 'Room label style',
        labelNumberFloorsToDisplay: 'Number of floors to display',
        lockPanning: 'Lock panning',
        fullScreen: 'Full screen',
        enableScreenshots: 'Enable screenshots'
      },
      roomLabelStyles: {
        Dark: 'Dark',
        Light: 'Light (Default)',
        DarkAndLarge: 'Large and Dark',
        LightAndLarge: 'Large and Light',
        DarkAndSmall: 'Small and Dark',
        LightAndSmall: 'Small and Light',
        DisplayNone: 'Turn Off',
        Learning: 'Learning Mode'
      },
      floorDisplayOptions: {
        one: '1 - Full',
        two: '2 - Split',
        four: '4 - Grid'
      },
      selectMaps: {
        selectAMap: 'Select a map',
        homeLink: 'Select a map'
      },
      compass: {
        letterN: 'N',
        letterE: 'E',
        letterS: 'S',
        letterW: 'W'
      },
      languages: {
        pc: 'Player Calls',
        en: 'English'
      },
      floorNames: {
        subBasement: { full: 'Sub-Basement', short: 'B'},
        basement: { full: 'Basement', short: 'B' },
        firstFloor: { full: '1st Floor', short: '1' },
        secondFloor: { full: '2nd Floor', short: '2' },
        thirdFloor: { full: '3rd Floor', short: '3' },
        fourthFloor: { full: '4th Floor', short: '4' },
        roof: { full: 'Roof', short: 'R' }
      },
      objectives: {
        bombShortA: 'A',
        bombShortB: 'B',
        bomb: 'Bomb',
        hostageShort: 'H',
        hostage: 'Hostage',
        secureShort: 'S',
        secure: 'Secure',
        showAll: 'Show All'
      },
      legend: {
        breakableWalls: 'Breakable walls',
        breakableFloorTraps: 'Breakable floor traps',
        ceilingHatches: 'Ceiling hatches',
        lineOfSightWalls: 'Line of sight or half walls',
        lineOfSightFloors: 'Line of sight floors',
        droneTunnels: 'Drone tunnels',
        objectives: 'Objectives',
        insertionPoints: 'Insertion points',
        securityCameras: 'Security cameras',
        skylights: 'Skylights',
        onFloorAboveOrBelow: 'On floor above or below',
        cameraLineOfSight: 'Camera line of sight',
        ladders: 'Ladders'
      },
      spawnPoints: {
        a: 'A',
        b: 'B',
        c: 'C',
        d: 'D',
        e: 'E'
      },
      toggle: {
        labels: {full: 'Learning Mode', short: 'Learning', shortcut: ['l','L']}
      },
      mapNames: {
        bank: 'Bank',
        bartlett: 'Bartlett U.',
        border: 'Border',
        chalet: 'Chalet',
        club: 'Club House',
        consulate: 'Consulate',
        coastline: 'Coastline',
        favela: 'Favela',
        fortress: 'Fortress',
        hereford: 'Hereford',
        house: 'House',
        kanal: 'Kanal',
        kafe: 'Kafe Dostoyevsky',
        oregon: 'Oregon',
        outback: 'Outback',
        plane: 'Plane',
        skyscraper: 'Skyscraper',
        themepark: 'Theme Park',
        tower: 'Tower',
        villa: 'Villa',
        yacht: 'Yacht'
      },
      mapRooms: {
        bank: {
          spawnBoulevard: 'Boulevard',
          spawnBackAlley: 'Alley',
          printerRoom: 'Printer',
          parkingLot: 'Parking Lot',
          boulevard: 'Boulevard',
          jewelryFront: 'Jewelry',
          plaza: 'Plaza',
          mainEntrance: 'Main Entrance',
          garageRamp: 'Garage Ramp',
          exteriorParking: 'Parking',
          garageRoof: 'Garage Roof',
          alleyAccess: 'Alley Access',
          backAlleyRooftop: 'Alley Rooftop',
          backAlley: 'Alley',
          highRoof: 'High Roof',
          lowRoof: 'Low Roof',
          vault: 'Vault',
          goldVault: 'Gold',
          serverRoomStairs: 'Blue Stairs',
          serverRoom: 'Server',
          CCTVRoom: 'CCTV',
          loadingDock: 'Dock',
          secureHallway: 'Gold Hallway',
          sewer: 'Tunnel',
          lockers: 'Lockers',
          vaultLobby: 'Vault Lobby',
          vaultEntrance: 'Vault Entrance',
          mainStairway: 'Main Stairs',
          bankGarage: 'Garage',
          elevators: 'Elevators',
          tellersOffice: 'Tellers\' Office',
          archives: 'Archives',
          tellers: 'Tellers',
          loanOffice: 'Loan',
          officeHallway: 'Open Space Hallway',
          skylightStairwell: 'Square',
          lobby: 'Lobby',
          openArea: 'Open Space',
          staffRoom: 'Kitchen',
          electricalRoom: 'Electrical',
          adminOffice: 'Admin',
          ATMs: 'ATMs',
          executiveHallway: 'Lounge Hallway',
          frontDesk: 'Front Desk',
          executiveLounge: 'Lounge',
          CEOOffice: 'CEO',
          janitorCloset: 'Janitor',
          hallway: 'Meeting Hallway',
          terrace: 'Terrace',
          stockTradingRoom: 'Stock',
          conferenceRoom: 'Meeting',
          balcony: 'Banana',
          squareStairs: 'Square Stairs',
          lobbyStairs: 'Lobby Stairs',
          redTruck: 'Red Truck',
          lockersHallway: 'Lockers Hallway',
          stockHallway: 'Stock Hallway'
        },
        bartlett: {
          archwayHall: 'Archway Hall',
          archwaylHallway: 'Archway Hallway',
          backAlley: 'Back Alley',
          bathroom: 'Bath- room',
          campusField: 'Campus Field',
          classroom: 'Classroom',
          coatRoom: 'Coat Room',
          compassHallway: 'Compass Hallway',
          courtyard: 'Courtyard',
          centralHallway: 'Central Hallway',
          diningRoom: 'Dining Room',
          eastBalcony: 'East Balcony (not shown)',
          eastCorridor: 'East Corridor',
          eastStairs: 'East Stairs',
          festival: 'Festival',
          frontEntrance: 'Front Entrance',
          frontOffice: 'Front Office',
          frontPatio: 'Front Patio',
          gardenPass: 'Garden Pass',
          kitchen: 'Kitchen',
          lobby: 'Lobby',
          lounge: 'Lounge',
          lowerLibrary: 'Lower Library',
          mainGate: 'Main Gate',
          mainOffice: 'Main Office',
          modelHall: 'Model Hall',
          pantry: 'Pantry',
          parking: 'Parking',
          pianoRoom: 'Piano Room',
          readingRoom: 'Reading Room',
          roof: 'Roof',
          rowingMuseum: 'Rowing Museum',
          serviceRoom: 'Service Room',
          terrace: 'Terrace',
          trophyRoom: 'Trophy Room',
          upperLibrary: 'Upper Library',
          vistaHallway: 'Vista Hallway',
          westBalcony: 'West Balcony (not shown)',
          westCorridor: 'West Corridor'
        },
        border: {
          armoryLockers: 'Armory',
          tellers: 'Tellers',
          ventilationRoom: 'Ventilation',
          exitHallway: 'Exit',
          supplyCorridor: 'Supply Corridor',
          detention: 'Detention',
          customsInspection: 'Customs',
          customsDesk: 'Customs Desk',
          centralStairs: 'Main Stairs',
          serverRoom: 'Server',
          supplyRoom: 'Supply',
          workshop: 'Workshop',
          mainLobby: 'Lobby',
          bathroom: 'Bathroom',
          waitingRoom: 'Waiting',
          eastStairs: 'East Stairs',
          passportCheck: 'Passport',
          archives: 'Archives',
          offices: 'Offices',
          officesHallway: 'Offices Hallway',
          fountain: 'Fountain',
          mainHallway: 'Red Hallway',
          armoryDesk: 'Armory Desk',
          securityRoom: 'CCTV',
          breakRoom: 'Cafeteria',
          spawnEastVehicleEntrance: 'East Vehicle Entrance',
          spawnValley: 'Valley',
          spawnWestVehicleExit: 'West Vehicle Exit',
          westTower: 'West Tower',
          pedestrianExit: 'Pedestrian Exit',
          valley: 'Valley',
          parkingLotEntrance: 'Parkin Entrance',
          parkingLot: 'Parking',
          westRoad: 'West Road',
          vehicleCustoms: 'Vehicle Customs',
          crashScene: 'Crash',
          eastRoad: 'East Road',
          pedestrianEntrance: 'Pedestrian Entrance',
          pedestrianCustoms: 'Pedestrian Customs',
          watchTower: 'Watch Tower',
          eastAlley: 'East Alley',
          parkingLotAlley: 'Parking Alley',
          northBalcony: 'North Balcony',
          eastBalcony: 'East Balcony',
          westBalcony: 'West Balcony',
          southBalcony: 'South Balcony',
          roof: 'Roof',
          generator: 'Generator',
          bathroomHallway: 'Bathroom Hallway',
          archivesBalcony: 'Archives Balcony',
          busRoof: 'Bus Roof',
          waitingBalcony: 'Waiting Balcony',
          sandwich: 'Sandwich'

        },
        chalet: {
          spawnFrontYard: 'Front Yard',
          spawnCampfire: 'Campfire',
          spawnCliffside: 'Cliffside',
          spawnLakeside: 'Lakeside',
          libraryStairs: 'Library Stairs',
          snowmobileGarage: 'Garage',
          storageRoom: 'Storage',
          wineCellar: 'Wine',
          basementHallway: 'Basement Hallway',
          backyardStairs: 'Backyard Stairs',
          garageEntrance: 'Garage Entrance',
          gamingRoomHallway: 'Gaming Hallway',
          gamingRoom: 'Gaming',
          bar: 'Bar',
          diningRoom: 'Dining',
          trophyRoom: 'Trophy',
          kitchenHallway: 'Kitchen Hallway',
          kitchen: 'Kitchen',
          libraryHallway: 'Library Hallway',
          libraryEntrance: 'Library Entrance',
          library: 'Library',
          fireplaceHallway: 'Fireplace Hallway',
          bedroomHallway: 'Bedroom Hallway',
          masterBathroom: 'Bathroom',
          masterBedroom: 'Master',
          office: 'Office',
          woodenTrail: 'Wood Trail',
          campfireWood: 'Campfire Wood',
          backyard: 'Backyard',
          gazeebo: 'Gazebo',
          cliffsideStairs: 'Cliffside Stairs',
          cliffsideWoods: 'Cliffside Woods',
          backyardPatio: 'Back Patio',
          officeBalcony: 'Office Balcony',
          helipadTrail: 'Helipad Trail',
          helipad: 'Helipad',
          frontYardPatio: 'Front Patio',
          frontYard: 'Front Yard',
          bathroomBalcony: 'Bathroom Balcony',
          libraryBalcony: 'Library Balcony',
          snowmobiles: 'Snowmobiles',
          solarium: 'Solarium',
          fireplace: 'Fireplace',
          westMainEntrance: 'Main',
          pianoRoom: 'Piano',
          mezzanine: 'Mezzanine',
          trophyStairs: 'Trophy Stairs',
          diningHallway: 'Dining Hallway',
          mudroom: 'Mudroom',
          barStock: 'Stock',
          fireplaceStairs: 'Fireplace Stairs',
          blueHallway: 'Blue',
          carGarage: 'Car Garage',
          mainGarageEntrance: 'Car<br/>Garage<br/>Entrance',
          westMainStairs: 'Main Stairs',
          cliffside: 'Cliffside',
          campfire: 'Campfire',
          garageStairs: 'Garage Stairs',
          blueStairs: 'Blue Stairs',
          barHallway: 'Bar Hallway'
        },
        club: {
          // EXT
          mainGate: 'Main Gate',
          junkyard: 'Junkyard',
          vipParking: 'VIP Parking',
          parking: 'Parking',
          kennels: 'Kennels',
          warehouse: 'Warehouse',
          shippingDock: 'Shipping Dock',
          recreationArea: 'Recreation',
          trash: 'Trash',
          graffitiArea: 'Graffiti',
          constructionSite: 'Construction Site',

          // Stairs
          easternStairs: 'Red Stairs',
          blueStairs: 'Blue Stairs',
          centralStairs: 'Main Stairs',

          // Basement
          oilPit: 'Ladder',
          utilityRoom: 'Blue',
          memorialRoom: 'Bike',
          church: 'Church',
          basementHallway: 'Church Hallway',
          arsenalRoom: 'Armory',
          escapeTunnel: 'Tunnel',
          container: 'Container',
          bikeHallway: 'Bike Hallway',

          // 1F
          garage: 'Garage',
          sideEntrance: 'Side Entrance',
          changingRoom: 'Changing',
          stripClub: 'Strip Club',
          lobby: 'Lobby',
          frontPorch: 'Porch',
          lounge: 'Lounge',
          junkyardEntrance: 'Junkyard<br/>Entrance',
          garageStorage: 'Storage',
          poolTable: 'Pool',
          bar: 'Bar',
          stage: 'Stage',
          stockRoom: 'Stock',
          westernHallway: 'Srip Hallway',
          toilets: 'Toilets',
          centralHallway: 'Kitchen Hallway',
          kitchen: 'Kitchen',
          kitchenEntrance: 'Kitchen<br/>Entrance',

          // 2F
          westernRoof: 'Strip Roof',
          centralSubroof: 'Porch',
          cctvRoom: 'CCTV',
          easternSubroof: 'Blacony',
          gym: 'Gym',
          bedroom: 'Bedroom',
          construction: 'Construction',
          cashRoom: 'Cash',
          balcony: 'Jacuzzi',
          bedroomHallway: 'Bedroom Hallway',
          bathroom: 'Bathroom',
          secretStash: 'Secret',
          logisticOffice: 'Office',
          catwalk: 'Catwalk',

          // Roof
          easternRoof: 'Eastern Roof',
          centralRoof: 'Central Roof'

        },
        consulate: {
          spawnRiotBarricade: 'Riot Barricade',
          spawnPoliceLine: 'Police Line',
          spawnGasStation: 'Gas Station',
          spawnSideEntrance: 'Side Entrance',
          exitStairs: 'Yellow Stairs',
          garage: 'Garage',
          basementCorridor: 'Garage Corridor',
          securityRoom: 'Security',
          cafeteria: 'Kitchen',
          mainStairs: 'Spiral',
          lockerHallway: 'Locker',
          serviceStairs: 'Visa Stairs',
          electricRoom: 'Electric',
          storageRoom: 'Storage',
          archives: 'Archives',
          archivesCorridor: 'Archives Corridor',
          pressRoom: 'Piano',
          westCorridor: 'West Corridor',
          publicBathroom: 'Bathroom',
          antechamber: 'Antechamber',
          lobby: 'Lobby',
          eastCorridor: 'East Corridor',
          tellers: 'Tellers',
          visaOffice: 'Visa',
          visaEntrance: 'Visa Entrance',
          frontDoor: 'Front Door',
          balcony: 'Balcony',
          copyRoom: 'Copy',
          cabinet: 'Cabinet',
          administrationOffice: 'Admin',
          breakRoom: 'Break',
          frontOffice: 'Front Office',
          meetingRoom: 'Meeting',
          hallway: 'Long Desk',
          consulFrontDesk: 'Flag',
          privateBathroom: 'Top Bathroom',
          waitingRoom: 'Connector',
          consulateOffice: 'CEO',
          garageWay: 'Garage Way',
          courtyard: 'Courtyard',
          backCourtyard: 'Back Courtyard',
          sideEntrance: 'Side Entrance',
          dumpster: 'Dumpster',
          parking: 'Parking',
          gardens: 'Gardens',
          fountain: 'Fountain',
          emergencyExit: 'Yellow Entrance',
          garageRoof: 'Garage Roof',
          memorialGarden: 'Memorial',
          policeLine: 'Police',
          riotBarracade: 'Barracade',
          eastFrontYard: 'East Front Yard',
          westFrontYard: 'West Front Yard',
          frontAlley: 'Front Alley',
          buildingRoof: 'Roof',
          pillar: 'Pillar',
          whiteTruck: 'White Truck',
          pipes: 'Pipes'
        },
        coastline: {
          aquarium: 'Aquarium',
          backAlley: 'Back Alley',
          balcony: 'Aquarium Balcony',
          bathroom: 'Bathroom',
          billiardsRoom: 'Pool Table',
          blueBar: 'Blue Bar',
          cantina: 'Cantina',
          courtyard: 'Courtyard',
          djBooth: 'VIP Balcony',
          garageRoof: 'Garage Roof',
          hallOfFame: 'Guitars',
          hallway: 'Kitchen Hallway',
          hookahDeck: 'Hookah Balcony',
          hookahLounge: 'Hookah',
          kitchen: 'Kitchen',
          mainEntrance: 'Main Entrance',
          mainLobby: 'Lobby',
          northStairs: 'Blue Stairs',
          office: 'Library',
          penthouse: 'Penthouse',
          pool: 'Pool',
          poolEntrance: 'Pool Entrance',
          poolSide: 'Pool Side',
          rooftop: 'Rooftop',
          ruins: 'Ruins',
          securityRoom: 'Security',
          serviceEntrance: 'Delivery',
          southHallway: 'Luggage',
          southPromenade: 'Promenade',
          southStairs: 'White Stairs',
          sunriseBar: 'Sunrise',
          sunRoom: 'Sun',
          theater: 'TV',
          terrace: 'Terrace',
          toilets: 'Toilets',
          vipLounge: 'VIP',
          walkway: 'Walkway',
          reception: 'Reception',
          roofDrop: 'Roof Drop',
          vipHallway: 'VIP Hallway',
          theaterHallway: 'TV Hallway',
          hookahHallway: 'Hookah Hallway',
          sunriseHallway: 'Sunrise Hallway'
        },
        favela: {
          packagingRoom: 'Packaging Room',
          footballApartment: 'Football Apartment',
          armoryRoom: 'Armory Room',
          auntsApartment: 'Aunt\'s Apartment',
          auntsBedroom: 'Aunt\'s Bedroom',
          growRoom: 'Grow Room',
          bikersApartment: 'Biker\'s Apartment',
          methLab: 'Meth Lab',
          footballBedroom: 'Football Bedroom',
          footballOffice: 'Football Office',
          bikersBedroom: 'Biker\'s Bedroom',
          backStairs: 'Back Stairs',
          auntsHall: 'Aunt\'s Hall',
          kidsRoom: 'Kids Room',
          mainStairs: 'Main Stairs',
          stairHall: 'Stair Hall',
          roof: 'Roof',
          laundryRoom: 'Laundry Room',
          vaultRoom: 'Vault Room',
          bikersGarage: 'Biker\'s Garage',
          backAlley: 'Back Alley',
          schoolAlley: 'School Alley',
          footballPitch: 'Football Pitch',
          market: 'Market',
          marketAlley: 'Market Alley',
          schoolRooftops: 'School Rooftops',
          street: 'Street',
          rooftops: 'Rooftops',
          courtyard: 'Courtyard',
          accessAlley: 'Access Alley',
          shop: 'Shop',
          marketRooftops: 'Market Rooftops'
        },
        fortress: {
          // Spawns
          mainGate: 'Main Gate',
          parking: 'Parking',
          garden: 'Garden',
          stable: 'Stable',
          // Within each section going from south west, east then north
          // EXT
          gardenPath: 'Garden Path',
          stablePath: 'Stable Path',
          cliffside: 'Cliffside',
          courtyardPath: 'Courtyard Path',
          cannonOverlook: 'Cannon Overlook',
          unloadingZone: 'Unloading Zone',
          frontEntrance: 'Front Entrance',
          // 1F
          laundryRoom: 'Laundry Room',
          hammam: 'Hammam',
          showers: 'Showers',
          hammamHallway: 'Hammam Hallway',
          cafeteria: 'Cafeteria',
          infirmary: 'Infirmary',
          kitchen: 'Kitchen',
          changingRoom: 'Changing Room',
          mainHallway: 'Main Hallway',
          waitingRoom: 'Waiting Room',
          sittingRoom: 'Sitting Room',
          diningRoom: 'Dining Room',
          courtyard: 'Courtyard',
          musicRoom: 'Music Room',
          lobby: 'Lobby',
          courtyardLadder: 'Courtyard Ladder',
          office: 'Office',
          // here because this only appears for 1f
          lobbyStairs: 'Lobby Stairs',
          oldTowerStairs: 'Old Tower Stairs',
          // 2F
          hammamRoof: 'Hammam Roof',
          shishaLounge: 'Shisha Lounge',
          shishaHallway: 'Shisha Hallway',
          centralStairsHall: 'Central Stairs Hall',
          dormitory: 'Dormitory',
          gamesRoom: 'Games Room',
          briefingRoom: 'Briefing Room',
          courtyardBalcony: 'Courtyard Balcony',
          museum: 'Museum',
          bathroom: 'Bathroom',
          commandersOffice: 'Commander\'s Office',
          bedroom: 'Bedroom',
          courtyardTower: 'Courtyard Tower',
          towerStairs: 'Tower Stairs',
          towerHallway: 'Tower Hallway',
          towerRenovation: 'Tower Renovation',
          // Roof
          oldRoof: 'Old Roof',
          oldTower: 'Old Tower',
          modernRoof: 'Modern Roof',
          westTower: 'West Tower',
          eastTower: 'East Tower',
          guardTower: 'Guard Tower',
          // Stairs
          centralStairs: 'Central Stairs'
        },
        hereford: {
          // EXT/Spawn
          controlTower: 'Control Tower',
          street: 'Street',
          spitfireCourtyard: 'Spitfire Courtyard',
          westCourtyard: 'West Courtyard',
          eastCourtyard: 'East Courtyard',
          barnyard: 'Barnyard',
          shootingRange: 'Shooting Range',
          // Stairs
          mainStairs: 'Main Stairs',
          blueStairs: 'Blue Stairs',
          // 4F/Roof
          rooftop: 'Rooftop',
          // 3F
          tractorStorage: 'Tractor Storage',
          attic: 'Attic',
          ammoStorage: 'Ammo Storage',
          // 2F
          balcony: 'Balcony',
          loomRoom: 'Loom Room',
          laundryRoom: 'Laundry Room',
          garageRoof: 'Garage Roof',
          loomCloset: 'Loom Closet',
          blueHallway: 'Blue Hallway',
          masterBedroom: 'Master Bedroom',
          kidsRoom: 'Kids Room',
          bathroom: 'Bathroom',
          sewingRoom: 'Sewing Room',
          // 1F
          prepArea: 'Prep Area',
          kitchen: 'Kitchen',
          diningRoom: 'Dining Room',
          garage: 'Garage',
          kitchenEntrance: 'Kitchen Entrance',
          pianoRoom: 'Piano Room',
          livingRoom: 'Living Room',
          foyer: 'Foyer',
          // Basement
          eastTunnel: 'East Tunnel',
          fermentationChamber: 'Fermentation Chamber',
          generatorRoom: 'Generator Room',
          workshop: 'Workshop',
          mainHallway: 'Main Hallway',
          westTunnel: 'West Tunnel',
          brewery: 'Brewery',
          barrelStorage: 'Barrel Storage',
          barn: 'Barn'
        },
        house: {
          // EXT
          spawnFrontStreet: 'Front Street',
          spawnAPCArea: 'APC Area',
          spawnSideStreet: 'Side Street',
          sideStreet: 'Side Street',
          garageEntrance: 'Garage Entrance',
          garageSide: 'Garage Side',
          apcArea: 'APC Area',
          treeHouseAlley: 'Treehouse Alley',
          patio: 'Patio',
          basementStairs: 'Basement Stairs',
          frontYard: 'Front Yard',
          frontStreet: 'Front Street',
          frontBalcony: 'Front Balcony',
          readingRoomBalcony: 'Reading R. Balcony',
          backPorch: 'Back Porch',
          backPorchTop: 'Back Porch Top',
          // Stairs
          kitchenStairs: 'Kitchen Stairs',
          lobbyStairs: 'Lobby Stairs',
          backStairs: 'Back Stairs',
          redStairs: 'Red Stairs',
          // Basement
          depot: 'Depot',
          gym: 'Gym',
          laundryRoom: 'Laundry Room',
          garage: 'Garage',
          // 1F
          gameRoom: 'Game Room',
          backEntrance: 'Back Entrance',
          lobby: 'Lobby',
          kitchen: 'Kitchen',
          office: 'Office',
          diningRoom: 'Dining Room',
          musicRoom: 'Music Room',
          tvRoom: 'TV Room',
          connector: 'Connector',
          // 2F
          pinkRoom: 'Pink Room',
          girlsWalkIn: 'Girls\' Walk In',
          carRoom: 'Car Room',
          playRoom: 'Play Room',
          upperHallway: 'Upper Hallway',
          walkIn: 'Walk In',
          masterBedroom: 'Master Bedroom',
          readingRoom: 'Reading Room',
          bathroom: 'Bathroom',
          bathroomHallway: 'Bathroom Hallway',
          // 3F/Roof
          rooftop: 'Rooftop'
        },
        kanal: {
          // EXT
          sailboats: 'Sailboats',
          middleRoad: 'Middle',
          parking: 'Parking',
          frontLawn: 'Lawn',
          lockGateTunnel: 'Lock Gate Tunnel',
          forkliftAlley: 'Forklift',
          parkingEntrance: 'Parking Entrance',
          lockGate: 'Lock Gate',
          constructionSite: 'Construction',
          garage: 'Garage',
          divingAlcove: 'Alcove',
          quayContainers: 'Containers',
          floatingDock: 'Dock',
          docksBridge: 'Docks Bridge',
          lawnStairs: 'Lawn Stairs',
          // Stairs
          whiteStairs: 'White Stairs',
          redStairs: 'Red Stairs',
          greenStairs: 'Green Stairs',
          yellowStairs: 'Yellow Stairs',
          blueStairs: 'Blue Stairs',
          // 3F/Roof
          controlRoomRoof: 'East Roof',
          upperBridgeRoof: 'Upper Bridge Roof',
          // 2F
          coastGuardRoof: 'West Roof',
          balconyRenovations: 'Balcony Renovations',
          bridgeRoof: 'Bridge Roof',
          balcony: '"L"',
          renovations: 'Renovations',
          roofEntrance: 'Roof Entrance',
          controlRoomHallway: 'Radar Corridor',
          radarRoom: 'Radar',
          serverRoom: 'Server',
          serverRoomCorridor: 'Server Corridor',
          printerRoom: 'Printer',
          controlRoom: 'Control',
          upperBridge: 'Upper Bridge',
          // 1F
          archives: 'Archives',
          reception: 'Reception',
          modelRoom: 'Model',
          museum: 'Museum',
          coastGuardMeetingRoom: 'Meeting',
          radioRoomHallway: 'Radio Hallway',
          lowerBridge: 'Bridge',
          mapRoomCorridor: 'Map Corridor',
          securityRoom: 'Security',
          lounge: 'Lounge',
          mapRoom: 'Map',
          kitchen: 'Kitchen',
          constructionEntrance: 'Construction<br/>Entrance',
          radioRoom: 'Radio',
          projectorRoom: 'Projector',
          constructionStairs: 'Construction Stairs',
          gym: 'Gym',
          meetingRoomHallway: 'Meeting Hallway',
          // Basement
          pipes: 'Pipes',
          supplyRoomCorridor: 'Basement Corridor',
          bathroom: 'Bathroom',
          supplyRoom: 'Supply',
          showerCorridor: 'Shower',
          kayaks: 'Kayaks',
          lockerRoom: 'Locker',
          divingRoom: 'Diving',
          tunnel01: 'Tunnel',
          lawnEntrance: 'Lawn Entrance',
          divingCorridor: 'Diving Corridor'
        },
        kafe: {
          // EXT/Spawn
          backAlley: 'Back Alley',
          park: 'Park',
          christmasMarket: 'Market',
          garage: 'Garage',
          bakeryParking: 'Parking',
          bakeryRoof: 'Bakery Roof',
          terrace: 'Terrace',
          westMainStreet: 'West Street',
          mainStreet: 'Main Street',
          eastMainStreet: 'East Street',
          riverDocks: 'Docks',
          // Stairs
          whiteStairs: 'White Stairs',
          redStairs: 'Red Stairs',
          // 4F/Roof
          cafeRoofTop: 'Roof',
          redHatch: 'Red Hatch',
          newHatch: 'New hatch',
          // 3F
          cigarLounge: 'Piano',
          whiteCorridor: 'White Corridor',
          washrooms: 'Bathroom',
          barFreezer: 'Bar<br/>Freezer',
          cocktailLoungeEntrance: 'Cocktail Entrance',
          cocktailLounge: 'Cocktail',
          barBackstore: 'Storage',
          cigarShop: 'Cigar',
          cigarBalcony: 'Cigar Balcony',
          cocktailBalcony: 'Cocktail Balcony',
          bar: 'Bar',
          // 2F
          trainMuseum: 'Train',
          fireplaceHall: 'Dining',
          readingRoomCorridor: 'Reading Corridor',
          laundryRoom: 'Laundry',
          readingRoom: 'Reading',
          miningRoom: 'Mining',
          mainCorridor: 'Mining Corridor',
          pillarRoom: 'Pillar',
          museumEntrance: 'Red Corridor',
          fireplace: 'Fireplace',
          terraceEntrance: 'Terrace<br/>Entrance',
          main: 'Main',
          // 1F
          vipCorridor: 'VIP Corridor',
          bakery: 'Bakery',
          prepRoom: 'Prep',
          kitchenCooking: 'Cooking',
          kitchenService: 'Service',
          freezer: 'Freezer',
          vipSection: 'VIP',
          diningRoom: 'Restaurant',
          smallBakery: 'Small Bakery',
          coatCheck: 'Coat',
          reception: 'Reception',
          bottomBar: 'Bottom Bar',
          woodStairs: 'Wood Stairs',
          bakeryCorridor: 'Bakery Corridor'
        },
        oregon: {
          // EXT
          street: 'Street',
          junkyard: 'Junkyard',
          busYard: 'Bus',
          mainEntrance: 'Main Entrance',
          parking: 'Parking',
          constructionSite: 'Construction',
          farmlands: 'Garden',
          shootingRange: 'Shooting Range',

          // Stairs
          freezerStairs: 'Freezer Stairs',
          whiteStairs: 'White Stairs',
          laundryStairs: 'Laundry Stairs',
          mainStairs: 'Main Stairs',
          backStairs: 'Tower<br/>Stairs',
          towerStairs: 'Tower<br/>Stairs',

          // Basement
          laundryStorage: 'Storage',
          freezer: 'Freezer',
          laundryRoom: 'Laundry',
          basementCorridor: 'Basement Corridor',
          supplyCloset: 'Closet',
          supplyRoom: 'Supply',
          blueBunker: 'Blue',
          bunker: 'Bunker',
          boilerRoom: 'Pillar',
          electricRoom: 'Electric',

          // 1F
          classroom: 'Classroom',
          lobby: 'Lobby',
          showerCorridor: 'Shower Corridor',
          securityCorridor: 'Security Corridor',
          garage: 'Garage',
          smallTower: 'Small Tower',
          showers: 'Showers',
          security: 'Security',
          diningHall: 'Dining',
          kitchen: 'Kitchen',
          meetingHall: 'Meeting',
          split: 'Split',
          kitchenCorridor: 'Kitchen Corridor',
          rearStage: 'Tower',
          stage: 'Stage',
          smallStairs: 'Small Stairs',

          // 2F
          balcony: 'Balcony',
          diningHallRoof: 'Dining Roof',
          walkIn: 'Walk In',
          masterBedroom: 'Master',
          smallTowerRoof: 'Small Tower Roof',
          dormMainHall: 'Dorm',
          gameRoom: 'Gaming',
          armory: 'Armory',
          armoryCorridor: 'Armory Corridor',
          smallTowerOffice: 'Office',
          trophyRoom: 'Trophy',
          kidsDorms: 'Kids',
          attic: 'Attic',
          meetingHallRoof: 'Meeting Roof',
          bigTower: 'Cat Walk',
          middle: 'Middle',

          // 3F
          dormsRoof: 'Dorms Roof',
          garageRoof: 'Garage Roof',
          towerRoof: 'Tower Roof',
          atticRoof: 'Attic Roof'
        },
        outback: {
          // EXT
          gasPumps: 'Gas Pumps',
          motelParkingLot: 'Motel Parking Lot',
          restaurantParking: 'Restaurant Parking',
          motelWalkway: 'Motel Walkway',
          restaurantEntrance: 'Restaurant Entrance',
          camping: 'Camping',
          loadingBay: 'Loading Bay',
          picnicArea: 'Picnic Area',
          miniGolf: 'Mini Golf',
          storageYard: 'Storage Yard',

          // 1F
          garage: 'Garage',
          waitingRoom: 'Waiting Room',
          convenienceStore: 'Convenience Store',
          beerFridge: 'Beer Fridge',
          gearStore: 'Gear Store',
          compressorRoom: 'Compressor Room',
          motelReception: 'Motel Reception',
          reptileHallway: 'Reptile Hallway',
          kitchen: 'Kitchen',
          restaurant: 'Restaurant',
          backEntrance: 'Back Entrance',
          bushrangerRoom: 'Bushranger Room',
          natureRoom: 'Nature Room',
          restaurantLobby: 'Rest- aurant Lobby',
          kitchenHallway: 'Kitchen Hallway',
          bathroomHall: 'Bath- room Hall',
          closet: 'Closet',
          bathroom: 'Bathroom',

          // 2F
          garageLounge: 'Garage Lounge',
          convenienceStoreRoof: 'Convenience Store Roof',
          motelBalcony: 'Motel Balcony',
          office: 'Office',
          officeSupplies: 'Office Supplies',
          mechanicalBull: 'Mechanical Bull',
          partyRoom: 'Party Room',
          electricalRoom: 'Electrical Room',
          gamesRoom: 'Games Room',
          dorms: 'Dorms',
          showers: 'Showers',
          mezzanine: 'Mezzanine',
          laundry: 'Laundry',
          motelHallway: 'Motel Hallway',
          pianoRoom: 'Piano Room',
          terrace: 'Terrace',

          // 3F/Roof
          restaurantRoof: 'Restaurant<br>Roof',
          garageRoof: 'Garage Roof',
          motelRoof: 'Motel Roof',

          // Stairs
          garageStairs: 'Garage Stairs',
          motelBackStairs: 'Motel Back Stairs',
          backStairs: 'Back Stairs',
          pianoStairs: 'Piano Stairs',
          restaurantStairs: 'Restaurant Stairs',
          terraceStairs: 'Terrace Stairs'
        },
        plane: {
          spawnOfficialEntrance: 'Official Entrance',
          spawnReporterEntrance: 'Reporter Entrance',
          spawnServiceEntrance: 'Service Entrance',
          pressBathroom: 'Pr.BR',
          meetingRoom: 'Meeting Room',
          frontHallway: 'Front Hallway',
          executiveOffice: 'Executive Office',
          mainEntrance: 'Main Entrance',
          frontStairs: 'Front Stairs',
          pantry: 'Pantry',
          kitchen: 'Kitchen',
          executiveHallway: 'Executive Hallway',
          executiveBedroom: 'Executive Bedroom',
          changeRoom: 'Change Room',
          laund: 'Laund.',
          frontServiceEntrance: 'Front Service Entrance',
          rightWing: 'Right Wing',
          backServiceEntrance: 'Back Service Entrance',
          reporterEntrance: 'Reporter Entrance',
          leftWing: 'Left Wing',
          staffSection: 'Staff Section',
          securityRoom: 'Security Room',
          pressSectionA: 'Press Section A',
          pressSectionB: 'Press Section B',
          backStairs: 'Back Stairs',
          cargoHold: 'Cargo Hold',
          serviceCorridor: 'Service Corridor',
          storage: 'Storage',
          luggageHold: 'Luggage Hold',
          firstAidStation: 'First Aid Station',
          cargoFrontEntrance: 'Cargo Front Entrance',
          cockpitStairs: 'Cockpit Stairs',
          cabinStaff: 'Cabin Staff',
          radioCabin: 'Radio Cabin',
          cabin: 'Cabin',
          caterer: 'Caterer',
          serverRoomA: 'Server Room A',
          serverRoomB: 'Server Room B',
          technicalSeating: 'Technical Seating',
          ladderRoom: 'Ladder Room'
        },
        skyscraper: {
          helipad: 'Helipad',
          tower: 'Tower',
          ventilationUnits: 'Ventilation',
          kitchen: 'Kitchen',
          pantry: 'Pantry',
          deliveryRoom: 'Delivery',
          houseLobby: 'Lobby',
          houseEntrance: 'House Entrance',
          mainEntrance: 'Main Entrance',
          reception: 'Reception',
          bedroom: 'Bedroom',
          bathroom: 'Bathroom',
          houseStairs: 'Lobby Stairs',
          restaurant: 'Restaurant',
          toilet: 'Toilet',
          bbq: 'BBQ',
          backHallway: 'Back Hallway',
          geishaRoom: 'Geisha',
          hallway: 'Geisha Hallway',
          karaoke: 'Karaoke',
          teaRoom: 'Tea',
          terrace: 'Terrace',
          backStairs: 'Karaoke Stairs',
          houseBalcony: 'House Balcony',
          lounge: 'Lounge',
          clearance: 'Clearance',
          peacefullTree: 'Tree',
          contemplationGarden: 'Contemplation',
          westGarden: 'West Garden',
          bridge: 'Bridge',
          gazeebo: 'Gazebo',
          northGarden: 'North Garden',
          eastGarden: 'East Garden',
          sandGarden: 'Sand',
          sidePath: 'Side Path',
          sideStairs: 'Side Stairs',
          drums: 'Drums',
          geisha: 'Geisha',
          makeupRoom: 'Makeup',
          shrineBalcony: 'Shrine Balcony',
          officeBalcony: 'Office Balcony',
          geishaBalcony: 'Geisha Balcony',
          terraceBalcony: 'Terrace Balcony',
          restaurantStairs: 'Geisha Stairs',
          mezzanine: 'Mezzanine',
          shrine: 'Shrine',
          dragon: 'Dragon',
          office: 'Office',
          exhibitionRoom: 'Museum',
          display: 'Display',
          vipClearance: 'VIP',
          bar: 'Bar',
          sushiBar: 'Sushi',
          coatCheck: 'Coat',
          delivery: 'Delivery',
          walkIn: 'Dressing',
          bedroomCloset: 'Closet',
          sideEntrance: 'Lobby Entrance',
          karaokeHallway: 'Karaoke Hallway',
          kitchenBalcony: 'Kitchen Balcony'
        },
        themepark: {
          // EXT
          mainEntrance: 'Main Entrance',
          palms: 'Palms',
          roboCircuit: 'Robo',
          castleEntrance: 'Castle',
          bumperCars: 'Bumper',
          guestInfo: 'Guest',
          village: 'Village',
          sweetShop: 'Sweet',
          serviceEntrance: 'Service',
          teacups: 'Teacups',
          backAlley: 'Alley',

          // 1F
          arcadeEntrance: 'Arcade',
          barrelRoom: 'Barrel',
          throneRoom: 'Throne',
          maintenance: 'Maintenance',
          dragonStairs: 'Dragon Stairs',
          blueRoom: 'Blue',
          jointCorridor: 'Lab Corridor',
          armory: 'Armory',
          lab: 'Lab',
          redCorridor: 'Red Corridor',
          gongRoom: 'Gong',
          yellowCorridor: 'Yellow Corridor',
          tellers: 'Tellers',
          storage: 'Drug',
          arcadeToilet: 'Toilet',
          lockerRoom: 'Locker',
          toiletCorridor: 'Toilet Corridor',
          dragon: 'Dragon',
          oven: 'Oven',
          lockerCorridor: 'Locker Corridor',

          // 2F
          upperArcade: 'Top Arcade',
          breakRoom: 'Kitchen',
          initiationRoom: 'Initiation',
          controlRoom: 'Control',
          bunk: 'Bunk',
          dayCare: 'Day Care',
          waitingRoom: 'Waiting',
          cafeTerrace: 'Terrace',
          cashCorridor: 'Cash Corridor',
          office: 'Office',
          cashStash: 'Cash',
          cafeCorridor: 'Cafe Corridor',
          cafe: 'Cafe',
          officeShower: 'Showers',
          officeVault: 'Vault',
          bar: 'Bar',
          dragonTop: 'Dragon Top',
          cashBalcony: 'Cash Balcony',
          arcadeBalcony: 'Arcade Balcony',

          // Roof
          roof: 'Roof',
          controlHatch: 'Control Hatch',
          yellowHatch: 'Yellow Hatch',

          // Stairs
          arcadeStairs: 'Arcade Stairs',
          yellowStairs: 'Yellow Stairs'
        },
        tower: {
          // EXT/Spawn
          northRoof: 'North Roof',
          northRoofNotShown: 'North Roof (not shown)',
          southRoof: 'South Roof',
          southRoofNotShown: 'South Roof (now shown)',
          roofAccess: 'Roof Access',
          northRappel: 'North Rappel',
          southRappel: 'South Rappel',
          // 3F
          mezzanine: 'Mezzanine',
          ventilation: 'Ventilation',
          // 2F
          centerAtrium: 'Center Atrium',
          infoBooth: 'Info Booth',
          eastAtrium: 'East Atrium',
          westAtrium: 'West Atrium',
          eastBalcony: 'East Balcony',
          westBalcony: 'West Balcony',
          galleryMain: 'Gallery Main',
          mediaCenter: 'Media Center',
          galleryAnnex: 'Gallery Annex',
          giftShop: 'Gift Shop',
          exhibitRoom: 'Exhibit Room',
          lanternRoom: 'Lantern Room',
          elevator: 'Elevator',
          officesHallway: 'Offices Hallway',
          exhibitHallway: 'Exhibit Hallway',
          offices: 'Offices',
          companyReception: 'Company Reception',
          supplyRoom: 'Supply Room',
          meetingRoom: 'Meeting Room',
          ceoOffice: 'CEO\'s Office',
          bathroom: 'Bathroom',
          serverRoom: 'Server Room',
          // 2F to 1F Stairs
          northStairs: 'North Stairs',
          westStairs: 'West Stairs',
          eastStairs: 'East Stairs',
          // 1F
          mainReception: 'Main Reception',
          centerHallway: 'Center Hallway',
          teaRoom: 'Tea Room',
          lounge: 'Lounge',
          bar: 'Bar',
          kitchen: 'Kitchen',
          restaurant: 'Restaurant',
          birdRoom: 'Bird Room',
          restaurantReception: 'Restaurant Reception',
          restaurantHallway: 'Restaurant Hallway',
          barHallway: 'Bar Hallway',
          westObservatory: 'West Observatory',
          bonsaiRoom: 'Bonsai Room',
          traditionalHall: 'Traditional Hall',
          gameRoom: 'Game Room',
          eastObservatory: 'East Observatory',
          fountain: 'Fountain',
          //Air Ducts:
          northAirDuct: 'North Air Duct',
          eastAirDuct: 'East Air Duct',
          westAirDuct: 'West Air Duct'
        },
        villa: {
          // Spawn
          spawnMainRoad: 'Main Road',
          spawnRuins: 'Ruins',
          spawnFountain: 'Fountain',
          // EXT
          ruins: 'Ruins',
          roundabout: 'Roundabout',
          greenhouse: 'Greenhouse',
          frontEntrance: 'Front<br/>Entrance',
          roof: 'Roof',
          terrace: 'Terrace',
          cryptTunnel: 'Crypt Tunnel',
          crypt: 'Crypt',
          cryptEntrance: 'Crypt Entrance',
          garden: 'Garden',
          driveway: 'Driveway',
          mainRoad: 'Main Road',
          balcony: 'Balcony',
          pergola: 'Pergola',
          stableYard: 'Stable YArd',
          skylightRoof: 'Skyligh Roof',
          bedroomRoof: 'Bedroom Roof',
          chapel: 'Chapel',
          garage: 'Garage',
          fountain: 'Fountain',
          stable: 'Stable',
          cellarTunnel: 'Cellar Tunnel',
          sideRoad: 'Side Road',
          // 2F
          veranda: 'Veranda',
          classicalHall: 'Ninety',
          study: 'Study',
          gamesRoom: 'Gaming',
          aviatorRoom: 'Aviator',
          huntingVault: 'Vault',
          landing: 'Landing',
          trophyEntrance: 'Trophy<br/>Entrance',
          statuaryRoom: 'Statue',
          trophyRoom: 'Trophy',
          masterBedroom: 'Master',
          astronomyRoom: 'Astro',
          masterBathroom: 'Bathroom',
          walkInCloset: 'Closet',
          ninetyCorner: 'Ninety<br/>Corner',
          bar: 'Bar',
          // 1F
          mainEntrance: 'Main',
          artStudio: 'Studio',
          library: 'Library',
          mainHallway: 'Piano Hallway',
          pianoRoom: 'Piano',
          gallery: 'Gallery',
          toilet: 'Toilet',
          livingRoom: 'Living',
          bicycleStorage: 'Bicycle',
          memorialRoom: 'Memorial',
          mudroom: 'Mudroom',
          skylightHallway: 'Living Hallway',
          laundry: 'Laundry',
          backHallway: 'Back Hallway',
          diningRoom: 'Dining',
          chinaRoom: 'China',
          kitchen: 'Kitchen',
          pantry: 'Pantry',
          astronomyStairs: 'Astro Stairs',
          // B
          tastingRoom: 'Tasting',
          archHallway: 'Arch',
          artStorage: 'Art',
          oldOffice: 'Office',
          wineCellar: 'Wine',
          // Stairs
          mainStairs: 'Main Stairs',
          redStairs: 'Red Stairs',
          backStairs: 'Back Stairs',
          pantryStairs: 'Pantry Stairs'
        },
        yacht: {
          spawnSubmarine: 'Submarine',
          spawnZodiak: 'Zodiak',
          spawnSnowMobile: 'Snow Mobile',
          mapsRoom: 'Maps Room',
          cockpit: 'Cockpit',
          cockpitHallway: 'Cockpit Hallway',
          captainsOffice: 'Captain\'s Office',
          cockpitBalcony: 'Cockpit Balcony',
          topDeckStairs: 'Top Deck Stairs',
          helipadEntrance: 'Helipad Entrance',
          helipad: 'Helipad',
          spaDeck: 'Spa Deck',
          eastDeck: 'East Deck',
          westDeck: 'West Deck',
          frontDeck: 'Front Deck',
          masterBedroom: 'Master Bedroom',
          casino: 'Casino',
          pokerRoom: 'Poker Room',
          bathroom: 'Bath- room',
          bedroomHallway: 'Bedroom Hallway',
          casinoHallway: 'Casino Hallway',
          globeHallway: 'Globe Hallway',
          lounge: 'Lounge',
          cafeteria: 'Cafeteria',
          engine: 'Engine',
          backEntrance: 'Back Entrance',
          rearDeck: 'Rear Deck',
          serverRoom: 'Server Room',
          engineStorage: 'Engine Storage',
          engineControl: 'Engine Control',
          backStairs: 'Back Stairs',
          emergencyExit: 'Emergency Exit',
          engineHallway: 'Engine Hallway',
          frontStairs: 'Front Stairs',
          kitchen: 'Kitchen',
          staffDormitory: 'Staff Dormitory',
          westBalcony: 'West Balcony',
          eastBalcony: 'East Balcony',
          kitchenHallway: 'Kitchen Hallway',
          kitchenStairs: 'Kitchen Stairs',
          kitchenPantry: 'Kitchen Pantry',
          infirmary: 'Infirmary',
          borealSubRoom: 'Boreal Sub Room',
          cafeteriaHallway: 'Cafeteria Hallway',
          engineUtility: 'Engine Utility',
          submarine: 'Submarine',
          westGlacier: 'West Glacier',
          eastHullBreach: 'East Hull Breach',
          eastGlacier: 'East Glacier',
          frozenRiver: 'Frozen River',
          zodiac: 'Zodiac',
          westHullBreach: 'West Hull Breach',
          kingOfTheWorld: 'King of the World',
          roof: 'Roof',
          anchorName: 'Anchor',
          aklarkSubEntrance: 'Aklark Sub Entrance'
        }
      }
    };

  var getLoadedLang = function getLoadedLang() {
    return loadedLang;
  };

  var getLoadedDirection = function getLoadedDirection() {
    return loadedDirection;
  };

  var registerLanguage = function registerLanguage(language, terms, direction) {
    translations[language] = {
      terms: terms,
      direction: (direction === 'RTL') ? 'RTL' : 'LTR'
    };
  };

  var tryLoadLanguage = function tryLoadLanguage(language) {
    if (translations[language]) {
      loadTerms(translations[language].terms);
      loadedLang = language;
      loadedDirection = translations[language].direction;
    }
  };

  var loadTerms = function loadTerms(newTerms) {
    loadDefaultTerms();
    $.extend(true, terms, newTerms);
  };

  var loadDefaultTerms = function loadDefaultTerms() {
    $.extend(true, terms, callTerms);
  };

  registerLanguage(name, callTerms);
  loadDefaultTerms();

  return  {
    name: name,
    getLoadedLang: getLoadedLang,
    getLoadedDirection: getLoadedDirection,
    terms: terms,
    registerLanguage: registerLanguage,
    tryLoadLanguage: tryLoadLanguage,
    loadedLanguages: translations
  };
})();
