'use strict';

var R6MLangTermsLearningCalls = (function(undefined) {
  var name = 'lr',
    terms = {
      general: {
        pageTitle: 'R6Maps.com - {mapName}',
        pageTitleSelectMap: 'R6Maps.com - Select a map',
        pageTitleStart: 'R6Maps.com',
        cameraViewCaption: '{floorName} Camera View',
        shortcutTip: 'Shortcut: {shortcut}',
        menu: 'Menu',
        about: 'About',
        languageHeader: 'Language',
        optionsHeader: 'Options',
        labelLosOpacity: 'Camera line-of-sight opacity',
        linkAbout: 'about/about.html',
        labelPercent: '{int}%', // according to: (0.12).toLocaleString('en', { style: 'percent' });
        labelLosDefault: '(Default)',
        labelLos105: '(Huh?)',
        labelLos110: '(Ludicrous!)',
        labelRoomLabelStyle: 'Room label style',
        labelNumberFloorsToDisplay: 'Number of floors to display',
        lockPanning: 'Lock panning',
        lockZooming: 'Lock zooming',
        fullScreen: 'Full screen',
        enableScreenshots: 'Enable screenshots',
        contributions: 'Contributions',
        supportSiteNote: 'Please consider showing your support with a small donation. :)',
        donateImg: 'https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif',
        latestUpdate: 'Feb 2017 updates',
        linkLatestUpdate: 'about/updates/2017-Feb/index.html'
      },
      sessions: {
        button: 'Sessions (BETA)'
      },
      roomLabelStyles: {
        Dark: 'Dark',
        Light: 'Light (Default)',
        DarkAndLarge: 'Large and Dark',
        LightAndLarge: 'Large and Light',
        DarkAndSmall: 'Small and Dark',
        LightAndSmall: 'Small and Light',
        DisplayNone: 'Turn Off'
      },
      floorDisplayOptions: {
        one: '1 - Full',
        two: '2 - Split',
        four: '4 - Grid'
      },
      selectMaps: {
        selectAMap: 'Select a map',
        homeLink: 'Select a map'
      },
      compass: {
        letterN: 'N',
        letterE: 'E',
        letterS: 'S',
        letterW: 'W'
      },
      floorNames: {
        subBasement: { full: 'Sub-Basement', short: 'B'},
        basement: { full: 'Basement', short: 'B' },
        firstFloor: { full: '1st Floor', short: '1' },
        secondFloor: { full: '2nd Floor', short: '2' },
        thirdFloor: { full: '3rd Floor', short: '3' },
        fourthFloor: { full: '4th Floor', short: '4' },
        roof: { full: 'Roof', short: 'R' }
      },
      objectives: {
        bombShortA: 'A',
        bombShortB: 'B',
        bomb: 'Bomb',
        hostageShort: 'H',
        hostage: 'Hostage',
        secureShort: 'S',
        secure: 'Secure',
        showAll: 'Show All'
      },
      legend: {
        breakableWalls: 'Breakable walls',
        breakableFloorTraps: 'Breakable floor traps',
        ceilingHatches: 'Ceiling hatches',
        lineOfSightWalls: 'Line of sight or half walls',
        lineOfSightFloors: 'Line of sight floors',
        droneTunnels: 'Drone tunnels',
        objectives: 'Objectives',
        insertionPoints: 'Insertion points',
        securityCameras: 'Security cameras',
        skylights: 'Skylights',
        onFloorAboveOrBelow: 'On floor above or below',
        cameraLineOfSight: 'Camera line of sight',
        ladders: 'Ladders'
      },
      spawnPoints: {
        a: 'A',
        b: 'B',
        c: 'C',
        d: 'D',
        e: 'E'
      },
      stats: {
        title: 'R6Maps.com - Stats',
        titleBeta: 'R6Maps.com - Stats BETA',
        headerMain: 'Stats',
        headerMainBeta: 'Stats BETA',
        headerFilters: 'Filters',
        headerMap: 'Map Stats',
        headerOperators: 'Operators',
        headerAboutAndOptions: 'About/Options',
        headerWinReasons: '{role} Win Reasons',
        labelSeason: 'Season',
        labelPlatform: 'Platform',
        labelMap: 'Map',
        labelGameMode: 'Mode',
        labelObjectiveLocation: 'Location',
        allOption: 'All',
        seasonWithNumber: 'Season {0}',
        objectiveRoomDivider: ' / ',
        ellipsis: '...',
        loadButtonText: 'Load Stats',
        averageRoundLength: 'Average round length',
        numberSeconds: '{num} seconds',
        totalRoundsPlayed: 'Total rounds played',
        numberRounds: '{num} rounds',
        tableHeaderAttackers: 'Attackers',
        tableHeaderAttackersSingular: 'Attacker',
        tableHeaderDefenders: 'Defenders',
        tableHeaderDefendersSingular: 'Defender',
        tableHeaderName: 'Name',
        tableHeaderPickRate: 'Pick Rate',
        tableHeaderWinRate: 'Win Rate',
        tableHeaderSurvivalRate: 'Survival Rate',
        tableHeaderKillsPerDeath: 'Kills:Death',
        tableHeaderKillsPerRound: 'Kills:Round',
        tableHeaderTotalRounds: 'Total Rounds',
        tableHeaderAllRanks: 'All Ranks',
        tableNoteHeader: 'Notes:',
        tableNotePickRate: 'Pick rates by rank are approximate and based on the relative number of rounds played.',
        tableNoteHeaders: 'Click on headers for charts and subheaders for sort order.',
        tableNoteWarningText: 'Orange text indicates a less reliable stat based on very few rounds played.',
        tableFewRoundsNote: 'Less reliable (very few rounds played)',
        averagesAndTotals: 'Averages/Totals',
        percentageFormat: '{num}%',
        instructions: 'Select filter options and hit \'Load Stats\' to continue.',
        noResults: 'No results found.  Please adjust the filters or try again later.',
        error: 'There was an error trying to load stats.  Please try again later.',
        chartHeader: '{stat} for {role}',
        loadedInfoLine1AllPlatforms: 'Showing Stats for {season} on All Platforms',
        loadedInfoLine1SinglePlatform: 'Showing Stats for {season} on {platform}',
        loadedInfoLine2AllMapsAllModes: 'All Maps | All Modes',
        loadedInfoLine2SingleMapAllModes: '{map} | All Modes',
        loadedInfoLine2AllMapsSingleMode: 'All Maps | {mode}',
        loadedInfoLine2SingleMapSingleModeAllLocations: '{map} | {mode} | All Locations',
        loadedInfoLine2SingleMapSingleModeSingleLocation: '{map} | {mode} | {location}',
        aboutLinksHeader: 'Links',
        aboutR6MapsHome: 'R6Maps.com Home',
        aboutR6MapsAbout: 'R6Maps.com About',
        aboutBasedOnUbisoft: 'Ubisoft Data Peek Series',
        winRatesForMap: 'Win rates for {map}',
        detailedStatsLink: 'See detailed stats'
      },
      statsRoundWinReasons: {
        allTeamsDead: 'All teams dead',
        attackersEliminated: 'Enemy team killed',
        attackersKilledHostage: 'Hostage killed',
        attackersSurrendered: 'Surrender',
        bombDeactivated_OneBomb: 'Bomb deactivated',
        bombExploded: 'Bomb exploded',
        defendersEliminated: 'Enemy team killed',
        defendersKilledHostage: 'Hostage killed',
        defendersSurrendered: 'Surrender',
        defuserDeactivated: 'Defuser deactivated',
        hostageExtracted: 'Hostage extracted',
        noEnemies: 'No enemies',
        objectiveCaptured: 'Objective secured',
        objectiveProtected: 'Objective protected',
        timeExpired: 'Time expired'
      },
      toggle: {
        labels: {full: 'Toggle Labels', short: 'Labels', shortcut: ['t','T']}
      },
      ranks: {
        unranked: 'Unranked',
        copper: 'Copper',
        bronze: 'Bronze',
        silver: 'Silver',
        gold: 'Gold',
        platinum: 'Platinum',
        diamond: 'Diamond'
      },
      platforms: {
        pc: 'PC',
        xboxone: 'Xbox One',
        ps4: 'PS4'
      },
      seasons: {
        1: 'Black Ice',
        2: 'Dust Line',
        3: 'Skull Rain',
        4: 'Red Crow',
        5: 'Velvet Shell',
        6: 'Operation Health',
        7: 'Blood Orchid',
        8: 'White Noise',
        9: 'Chimera',
        10: 'Para Bellum',
        11: 'Grim Sky',
        12: 'Wind Bastion',
        13: 'Burnt Horizon',
        14: 'Phantom Sight',
        15: 'Ember Rise',
        16: 'Shifting Tides'
      },
      operators: {
        amaru: 'Amaru',
        ash: 'Ash',
        bandit: 'Bandit',
        blackbeard: 'Blackbeard',
        blitz: 'Blitz',
        buck: 'Buck',
        capitao: 'Capitao',
        castle: 'Castle',
        caveira: 'Caveira',
        doc: 'Doc',
        echo: 'Echo',
        ela: 'Ela',
        frost: 'Frost',
        fuze: 'Fuze',
        gignRecruit: 'GIGN Recruit',
        glaz: 'Glaz',
        goyo: 'Goyo',
        gridlock: 'Gridlock',
        gsg9Recruit: 'GSG9 Recruit',
        hibana: 'Hibana',
        iq: 'IQ',
        jackal: 'Jackal',
        jager: 'Jager',
        kaid: 'Kaid',
        kali: 'Kali',
        kapkan: 'Kapkan',
        lesion: 'Lesion',
        mira: 'Mira',
        montagne: 'Montagne',
        mozzie: 'Mozzie',
        mute: 'Mute',
        nokk: 'Nøkk',
        nomad: 'Nomad',
        pulse: 'Pulse',
        rook: 'Rook',
        sasRecruit: 'SAS Recruit',
        sledge: 'Sledge',
        smoke: 'Smoke',
        spetsnazRecruit: 'Spetsnaz Recruit',
        swatRecruit: 'SWAT Recruit',
        tachanka: 'Lord Tachanka',
        thatcher: 'Thatcher',
        thermite: 'Thermite',
        twitch: 'Twitch',
        valkyrie: 'Valkyrie',
        wamai: 'Wamai',
        warden: 'Warden',
        ying: 'Ying'
      },
      mapNames: {
        bank: 'Bank',
        bartlett: 'Bartlett U.',
        border: 'Border',
        chalet: 'Chalet',
        club: 'Club House',
        consulate: 'Consulate',
        coastline: 'Coastline',
        favela: 'Favela',
        fortress: 'Fortress',
        hereford: 'Hereford',
        house: 'House',
        kanal: 'Kanal',
        kafe: 'Kafe Dostoyevsky',
        oregon: 'Oregon',
        outback: 'Outback',
        plane: 'Plane',
        skyscraper: 'Skyscraper',
        themepark: 'Theme Park',
        tower: 'Tower',
        villa: 'Villa',
        yacht: 'Yacht'
      },
      mapRooms: {
        bank: {
          spawnBoulevard: '???',
          spawnBackAlley: '???',
          printerRoom: '???',
          parkingLot: '???',
          boulevard: '???',
          jewelryFront: '???',
          plaza: '???',
          mainEntrance: '???',
          garageRamp: '???',
          exteriorParking: '???',
          garageRoof: '???',
          alleyAccess: '???',
          backAlleyRooftop: '???',
          backAlley: '???',
          highRoof: '???',
          lowRoof: '???',
          vault: '???',
          goldVault: '???',
          serverRoomStairs: '???',
          serverRoom: '???',
          CCTVRoom: '???',
          loadingDock: '???',
          secureHallway: '???',
          sewer: '???',
          lockers: '???',
          vaultLobby: '???',
          vaultEntrance: '???',
          mainStairway: '???',
          bankGarage: '???',
          elevators: '???',
          tellersOffice: '???',
          archives: '???',
          tellers: '???',
          loanOffice: '???',
          officeHallway: '???',
          skylightStairwell: '???',
          lobby: '???',
          openArea: '???',
          staffRoom: '???',
          electricalRoom: '???',
          adminOffice: '???',
          ATMs: '???',
          executiveHallway: '???',
          frontDesk: '???',
          executiveLounge: '???',
          CEOOffice: '???',
          janitorCloset: '???',
          hallway: '???',
          terrace: '???',
          stockTradingRoom: '???',
          conferenceRoom: '???',
          balcony: '???',
          squareStairs: '???',
          lobbyStairs: '???'
        },
        bartlett: {
          archwayHall: '???',
          archwaylHallway: '???',
          backAlley: '???',
          bathroom: '???',
          campusField: '???',
          classroom: '???',
          coatRoom: '???',
          compassHallway: '???',
          courtyard: '???',
          centralHallway: '???',
          diningRoom: '???',
          eastBalcony: '???',
          eastCorridor: '???',
          eastStairs: '???',
          festival: '???',
          frontEntrance: '???',
          frontOffice: '???',
          frontPatio: '???',
          gardenPass: '???',
          kitchen: '???',
          lobby: '???',
          lounge: '???',
          lowerLibrary: '???',
          mainGate: '???',
          mainOffice: '???',
          modelHall: '???',
          pantry: '???',
          parking: '???',
          pianoRoom: '???',
          readingRoom: '???',
          roof: '???',
          rowingMuseum: '???',
          serviceRoom: '???',
          terrace: '???',
          trophyRoom: '???',
          upperLibrary: '???',
          vistaHallway: '???',
          westBalcony: '???',
          westCorridor: '???'
        },
        border: {
          armoryLockers: '???',
          tellers: '???',
          ventilationRoom: '???',
          exitHallway: '???',
          supplyCorridor: '???',
          detention: '???',
          customsInspection: '???',
          customsDesk: '???',
          centralStairs: '???',
          serverRoom: '???',
          supplyRoom: '???',
          workshop: '???',
          mainLobby: '???',
          bathroom: '???',
          waitingRoom: '???',
          eastStairs: '???',
          passportCheck: '???',
          archives: '???',
          offices: '???',
          officesHallway: '???',
          fountain: '???',
          mainHallway: '???',
          armoryDesk: '???',
          securityRoom: '???',
          breakRoom: '???',
          spawnEastVehicleEntrance: '???',
          spawnValley: '???',
          spawnWestVehicleExit: '???',
          westTower: '???',
          pedestrianExit: '???',
          valley: '???',
          parkingLotEntrance: '???',
          parkingLot: '???',
          westRoad: '???',
          vehicleCustoms: '???',
          crashScene: '???',
          eastRoad: '???',
          pedestrianEntrance: '???',
          pedestrianCustoms: '???',
          watchTower: '???',
          eastAlley: '???',
          parkingLotAlley: '???',
          northBalcony: '???',
          eastBalcony: '???',
          westBalcony: '???',
          southBalcony: '???',
          roof: '???'
        },
        chalet: {
          spawnFrontYard: '???',
          spawnCampfire: '???',
          spawnCliffside: '???',
          spawnLakeside: '???',
          libraryStairs: '???',
          snowmobileGarageCorridor: '???',
          snowmobileGarage: '???',
          greatRoomStairs: '???',
          storageRoom: '???',
          wineCellar: '???',
          wineStock: '???',
          basementHallway: '???',
          backyardStairs: '???',
          mainStairs: '???',
          mainGarage: '???',
          garageEntrance: '???',
          westEntrance: '???',
          gamingRoomHallway: '???',
          gamingRoom: '???',
          bar: '???',
          greatRoom: '???',
          diningRoom: '???',
          mainEntrance: '???',
          trophyRoom: '???',
          kitchenHallway: '???',
          kitchen: '???',
          libraryHallway: '???',
          libraryEntrance: '???',
          library: '???',
          bedroomTerrace: '???',
          fireplaceHallway: '???',
          bedroomHallway: '???',
          masterBathroom: '???',
          masterBedroom: '???',
          office: '???',
          woodenTrail: '???',
          campfireWood: '???',
          backyard: '???',
          gazeebo: '???',
          cliffsideStairs: '???',
          cliffsideWoods: '???',
          backyardPatio: '???',
          officeBalcony: '???',
          helipadTrail: '???',
          helipad: '???',
          frontYardPatio: '???',
          frontYard: '???',
          bathroomBalcony: '???',
          libraryBalcony: '???',
          bedroomBalcony: '???',
          snowmobiles: '???',
          solarium: '???',
          fireplace: '???',
          westMainEntrance: '???',
          pianoRoom: '???',
          mezzanine: '???',
          trophyStairs: '???',
          diningHallway: '???',
          mudroom: '???',
          barStock: '???',
          fireplaceStairs: '???',
          blueHallway: '???',
          carGarage: '???',
          mainGarageEntrance: '???',
          westMainStairs: '???',
          cliffside: '???',
          campfire: '???'
        },
        club: {
          // EXT
          mainGate: '???',
          junkyard: '???',
          vipParking: '???',
          parking: '???',
          kennels: '???',
          warehouse: '???',
          shippingDock: '???',
          recreationArea: '???',
          trash: '???',
          graffitiArea: '???',
          constructionSite: '???',

          // Stairs
          easternStairs: '???',
          blueStairs: '???',
          centralStairs: '???',

          // Basement
          oilPit: '???',
          utilityRoom: '???',
          memorialRoom: '???',
          church: '???',
          basementHallway: '???',
          arsenalRoom: '???',
          escapeTunnel: '???',
          container: '???',

          // 1F
          garage: '???',
          sideEntrance: '???',
          changingRoom: '???',
          stripClub: '???',
          lobby: '???',
          frontPorch: '???',
          lounge: '???',
          junkyardEntrance: '???',
          garageStorage: '???',
          poolTable: '???',
          bar: '???',
          stage: '???',
          stockRoom: '???',
          westernHallway: '???',
          toilets: '???',
          centralHallway: '???',
          kitchen: '???',
          kitchenEntrance: '???',

          // 2F
          westernRoof: '???',
          centralSubroof: '???',
          cctvRoom: '???',
          easternSubroof: '???',
          gym: '???',
          bedroom: '???',
          construction: '???',
          cashRoom: '???',
          balcony: '???',
          bedroomHallway: '???',
          bathroom: '???',
          secretStash: '???',
          logisticOffice: '???',

          // Roof
          easternRoof: '???',
          centralRoof: '???'

        },
        consulate: {
          spawnRiotBarricade: '???',
          spawnPoliceLine: '???',
          spawnGasStation: '???',
          spawnSideEntrance: '???',
          exitStairs: '???',
          garage: '???',
          basementCorridor: '???',
          securityRoom: '???',
          cafeteria: '???',
          mainStairs: '???',
          lockerHallway: '???',
          serviceStairs: '???',
          electricRoom: '???',
          storageRoom: '???',
          archives: '???',
          archivesCorridor: '???',
          pressRoom: '???',
          westCorridor: '???',
          publicBathroom: '???',
          antechamber: '???',
          lobby: '???',
          eastCorridor: '???',
          tellers: '???',
          visaOffice: '???',
          visaEntrance: '???',
          frontDoor: '???',
          balcony: '???',
          copyRoom: '???',
          cabinet: '???',
          administrationOffice: '???',
          breakRoom: '???',
          frontOffice: '???',
          meetingRoom: '???',
          hallway: '???',
          consulFrontDesk: '???',
          privateBathroom: '???',
          waitingRoom: '???',
          consulateOffice: '???',
          garageWay: '???',
          courtyard: '???',
          backCourtyard: '???',
          sideEntrance: '???',
          dumpster: '???',
          parking: '???',
          gardens: '???',
          fountain: '???',
          emergencyExit: '???',
          garageRoof: '???',
          memorialGarden: '???',
          policeLine: '???',
          riotBarracade: '???',
          eastFrontYard: '???',
          westFrontYard: '???',
          frontAlley: '???',
          buildingRoof: '???'
        },
        coastline: {
          aquarium: '???',
          backAlley: '???',
          balcony: '???',
          bathroom: '???',
          billiardsRoom: '???',
          blueBar: '???',
          cantina: '???',
          courtyard: '???',
          djBooth: '???',
          garageRoof: '???',
          hallOfFame: '???',
          hallway: '???',
          hookahDeck: '???',
          hookahLounge: '???',
          kitchen: '???',
          mainEntrance: '???',
          mainLobby: '???',
          northStairs: '???',
          office: '???',
          penthouse: '???',
          pool: '???',
          poolEntrance: '???',
          poolSide: '???',
          rooftop: '???',
          ruins: '???',
          securityRoom: '???',
          serviceEntrance: '???',
          southHallway: '???',
          southPromenade: '???',
          southStairs: '???',
          sunriseBar: '???',
          sunRoom: '???',
          theater: '???',
          terrace: '???',
          toilets: '???',
          vipLounge: '???',
          walkway: '???'
        },
        favela: {
          packagingRoom: '???',
          footballApartment: '???',
          armoryRoom: '???',
          auntsApartment: '???',
          auntsBedroom: '???',
          growRoom: '???',
          bikersApartment: '???',
          methLab: '???',
          footballBedroom: '???',
          footballOffice: '???',
          bikersBedroom: '???',
          backStairs: '???',
          auntsHall: '???',
          kidsRoom: '???',
          mainStairs: '???',
          stairHall: '???',
          roof: '???',
          laundryRoom: '???',
          vaultRoom: '???',
          bikersGarage: '???',
          backAlley: '???',
          schoolAlley: '???',
          footballPitch: '???',
          market: '???',
          marketAlley: '???',
          schoolRooftops: '???',
          street: '???',
          rooftops: '???',
          courtyard: '???',
          accessAlley: '???',
          shop: '???',
          marketRooftops: '???'
        },
        fortress: {
          // Spawns
          mainGate: '???',
          parking: '???',
          garden: '???',
          stable: '???',
          // Within each section going from south west, east then north
          // EXT
          gardenPath: '???',
          stablePath: '???',
          cliffside: '???',
          courtyardPath: '???',
          cannonOverlook: '???',
          unloadingZone: '???',
          frontEntrance: '???',
          // 1F
          laundryRoom: '???',
          hammam: '???',
          showers: '???',
          hammamHallway: '???',
          cafeteria: '???',
          infirmary: '???',
          kitchen: '???',
          changingRoom: '???',
          mainHallway: '???',
          waitingRoom: '???',
          sittingRoom: '???',
          diningRoom: '???',
          courtyard: '???',
          musicRoom: '???',
          lobby: '???',
          courtyardLadder: '???',
          office: '???',
          // here because this only appears for 1f
          lobbyStairs: '???',
          oldTowerStairs: '???',
          // 2F
          hammamRoof: '???',
          shishaLounge: '???',
          shishaHallway: '???',
          centralStairsHall: '???',
          dormitory: '???',
          gamesRoom: '???',
          briefingRoom: '???',
          courtyardBalcony: '???',
          museum: '???',
          bathroom: '???',
          commandersOffice: '???',
          bedroom: '???',
          courtyardTower: '???',
          towerStairs: '???',
          towerHallway: '???',
          towerRenovation: '???',
          // Roof
          oldRoof: '???',
          oldTower: '???',
          modernRoof: '???',
          westTower: '???',
          eastTower: '???',
          guardTower: '???',
          // Stairs
          centralStairs: '???'
        },
        hereford: {
          // EXT/Spawn
          controlTower: '???',
          street: '???',
          spitfireCourtyard: '???',
          westCourtyard: '???',
          eastCourtyard: '???',
          barnyard: '???',
          shootingRange: '???',
          // Stairs
          mainStairs: '???',
          blueStairs: '???',
          // 4F/Roof
          rooftop: '???',
          // 3F
          tractorStorage: '???',
          attic: '???',
          ammoStorage: '???',
          // 2F
          balcony: '???',
          loomRoom: '???',
          laundryRoom: '???',
          garageRoof: '???',
          loomCloset: '???',
          blueHallway: '???',
          masterBedroom: '???',
          kidsRoom: '???',
          bathroom: '???',
          sewingRoom: '???',
          // 1F
          prepArea: '???',
          kitchen: '???',
          diningRoom: '???',
          garage: '???',
          kitchenEntrance: '???',
          pianoRoom: '???',
          livingRoom: '???',
          foyer: '???',
          // Basement
          eastTunnel: '???',
          fermentationChamber: '???',
          generatorRoom: '???',
          workshop: '???',
          mainHallway: '???',
          westTunnel: '???',
          brewery: '???',
          barrelStorage: '???',
          barn: '???'
        },
        house: {
          // EXT
          // Construction Site and River Docks are commented out because they still exist in Training Grounds but not anywhere else.
          // spawnConstructionSite: '???',
          // spawnRiverDocks: '???',
          spawnFrontStreet: '???',
          spawnAPCArea: '???',
          spawnSideStreet: '???',
          sideStreet: '???',
          garageEntrance: '???',
          garageSide: '???',
          apcArea: '???',
          treeHouseAlley: '???',
          patio: '???',
          basementStairs: '???',
          frontYard: '???',
          frontStreet: '???',
          frontBalcony: '???',
          readingRoomBalcony: '???',
          backPorch: '???',
          backPorchTop: '???',
          // Stairs
          kitchenStairs: '???',
          lobbyStairs: '???',
          backStairs: '???',
          redStairs: '???',
          // Basement
          depot: '???',
          gym: '???',
          laundryRoom: '???',
          garage: '???',
          // 1F
          gameRoom: '???',
          backEntrance: '???',
          lobby: '???',
          kitchen: '???',
          office: '???',
          diningRoom: '???',
          musicRoom: '???',
          tvRoom: '???',
          connector: '???',
          // 2F
          pinkRoom: '???',
          girlsWalkIn: '???',
          carRoom: '???',
          playRoom: '???',
          upperHallway: '???',
          walkIn: '???',
          masterBedroom: '???',
          readingRoom: '???',
          bathroom: '???',
          bathroomHallway: '???',
          // 3F/Roof
          rooftop: '???'
        },
        kanal: {
          // EXT
          sailboats: '???',
          middleRoad: '???',
          parking: '???',
          frontLawn: '???',
          lockGateTunnel: '???',
          forkliftAlley: '???',
          parkingEntrance: '???',
          parkingAlley: '???',
          lockGate: '???',
          constructionSite: '???',
          garage: '???',
          divingAlcove: '???',
          quayContainers: '???',
          floatingDock: '???',
          docksBridge: '???',
          // Stairs
          // basementStairs: '???',
          whiteStairs: '???',
          redStairs: '???',
          greenStairs: '???',
          yellowStairs: '???',
          // printerStairs: '???',
          blueStairs: '???',
          // 3F/Roof
          controlRoomRoof: '???',
          upperBridgeRoof: '???',
          // 2F
          coastGuardRoof: '???',
          balconyRenovations: '???',
          bridgeRoof: '???',
          balcony: '???',
          renovations: '???',
          roofEntrance: '???',
          controlRoomHallway: '???',
          radarRoom: '???',
          serverRoom: '???',
          serverRoomCorridor: '???',
          printerRoom: '???',
          controlRoom: '???',
          upperBridge: '???',
          // 1F
          archives: '???',
          reception: '???',
          modelRoom: '???',
          museum: '???',
          coastGuardMeetingRoom: '???',
          radioRoomHallway: '???',
          lowerBridge: '???',
          mapRoomCorridor: '???',
          securityRoom: '???',
          lounge: '???',
          mapRoom: '???',
          kitchen: '???',
          constructionEntrance: '???',
          radioRoom: '???',
          projectorRoom: '???',
          // Basement
          pipes: '???',
          supplyRoomCorridor: '???',
          bathroom: '???',
          supplyRoom: '???',
          showerCorridor: '???',
          kayaks: '???',
          lockerRoom: '???',
          divingRoom: '???',
          tunnel01: '???'
        },
        kafe: {
          // EXT/Spawn
          backAlley: '???',
          park: '???',
          christmasMarket: '???',
          garage: '???',
          bakeryParking: '???',
          bakeryRoof: '???',
          terrace: '???',
          westMainStreet: '???',
          mainStreet: '???',
          eastMainStreet: '???',
          riverDocks: '???',
          // Stairs
          whiteStairs: '???',
          redStairs: '???',
          // 4F/Roof
          cafeRoofTop: '???',
          // 3F
          cigarLounge: '???',
          whiteCorridor: '???',
          washrooms: '???',
          barFreezer: '???',
          cocktailLoungeEntrance: '???',
          cocktailLounge: '???',
          barBackstore: '???',
          cigarShop: '???',
          bar: '???',
          cigarBalcony: '???',
          cocktailBalcony: '???',
          // 2F
          trainMuseum: '???',
          fireplaceHall: '???',
          readingRoomCorridor: '???',
          laundryRoom: '???',
          readingRoom: '???',
          miningRoom: '???',
          mainCorridor: '???',
          pillarRoom: '???',
          museumEntrance: '???',
          // 1F
          vipCorridor: '???',
          bakery: '???',
          prepRoom: '???',
          kitchenCooking: '???',
          kitchenService: '???',
          freezer: '???',
          vipSection: '???',
          //mainCorridor: '???',
          diningRoom: '???',
          smallBakery: '???',
          coatCheck: '???',
          reception: '???'
        },
        oregon: {
          // EXT
          street: '???',
          junkyard: '???',
          busYard: '???',
          mainEntrance: '???',
          parking: '???',
          constructionSite: '???',
          farmlands: '???',
          shootingRange: '???',

          // Stairs
          freezerStairs: '???',
          whiteStairs: '???',
          laundryStairs: '???',
          mainStairs: '???',
          backStairs: '???',
          towerStairs: '???',

          // Basement
          laundryStorage: '???',
          freezer: '???',
          laundryRoom: '???',
          basementCorridor: '???',
          supplyCloset: '???',
          supplyRoom: '???',
          blueBunker: '???',
          bunker: '???',
          boilerRoom: '???',
          electricRoom: '???',

          // 1F
          classroom: '???',
          lobby: '???',
          showerCorridor: '???',
          securityCorridor: '???',
          garage: '???',
          smallTower: '???',
          showers: '???',
          security: '???',
          diningHall: '???',
          kitchen: '???',
          meetingHall: '???',
          split: '???',
          kitchenCorridor: '???',
          rearStage: '???',
          stage: '???',

          // 2F
          balcony: '???',
          diningHallRoof: '???',
          walkIn: '???',
          masterBedroom: '???',
          smallTowerRoof: '???',
          dormMainHall: '???',
          gameRoom: '???',
          armory: '???',
          armoryCorridor: '???',
          smallTowerOffice: '???',
          trophyRoom: '???',
          kidsDorms: '???',
          attic: '???',
          meetingHallRoof: '???',
          bigTower: '???',

          // 3F
          dormsRoof: '???',
          garageRoof: '???',
          towerRoof: '???'
        },
        outback: {
          // EXT
          gasPumps: '???',
          motelParkingLot: '???',
          restaurantParking: '???',
          motelWalkway: '???',
          restaurantEntrance: '???',
          camping: '???',
          loadingBay: '???',
          picnicArea: '???',
          miniGolf: '???',
          storageYard: '???',

          // 1F
          garage: '???',
          waitingRoom: '???',
          convenienceStore: '???',
          beerFridge: '???',
          gearStore: '???',
          compressorRoom: '???',
          motelReception: '???',
          reptileHallway: '???',
          kitchen: '???',
          restaurant: '???',
          backEntrance: '???',
          bushrangerRoom: '???',
          natureRoom: '???',
          restaurantLobby: '???',
          kitchenHallway: '???',
          bathroomHall: '???',
          closet: '???',
          bathroom: '???',

          // 2F
          garageLounge: '???',
          convenienceStoreRoof: '???',
          motelBalcony: '???',
          office: '???',
          officeSupplies: '???',
          mechanicalBull: '???',
          partyRoom: '???',
          electricalRoom: '???',
          gamesRoom: '???',
          dorms: '???',
          showers: '???',
          mezzanine: '???',
          laundry: '???',
          motelHallway: '???',
          pianoRoom: '???',
          terrace: '???',

          // 3F/Roof
          restaurantRoof: '???',
          garageRoof: '???',
          motelRoof: '???',

          // Stairs
          garageStairs: '???',
          motelBackStairs: '???',
          backStairs: '???',
          pianoStairs: '???',
          restaurantStairs: '???',
          terraceStairs: '???'
        },
        plane: {
          spawnOfficialEntrance: '???',
          spawnReporterEntrance: '???',
          spawnServiceEntrance: '???',
          pressBathroom: '???',
          meetingRoom: '???',
          frontHallway: '???',
          executiveOffice: '???',
          mainEntrance: '???',
          frontStairs: '???',
          pantry: '???',
          kitchen: '???',
          executiveHallway: '???',
          executiveBedroom: '???',
          changeRoom: '???',
          laund: '???',
          frontServiceEntrance: '???',
          rightWing: '???',
          backServiceEntrance: '???',
          reporterEntrance: '???',
          leftWing: '???',
          staffSection: '???',
          securityRoom: '???',
          pressSectionA: '???',
          pressSectionB: '???',
          backStairs: '???',
          cargoHold: '???',
          serviceCorridor: '???',
          storage: '???',
          luggageHold: '???',
          firstAidStation: '???',
          cargoFrontEntrance: '???',
          cockpitStairs: '???',
          cabinStaff: '???',
          radioCabin: '???',
          cabin: '???',
          caterer: '???',
          serverRoomA: '???',
          serverRoomB: '???',
          technicalSeating: '???',
          ladderRoom: '???'
        },
        skyscraper: {
          helipad: '???',
          tower: '???',
          ventilationUnits: '???',
          kitchen: '???',
          pantry: '???',
          deliveryRoom: '???',
          houseLobby: '???',
          houseEntrance: '???',
          mainEntrance: '???',
          reception: '???',
          bedroom: '???',
          closet: '???',
          bathroom: '???',
          houseStairs: '???',
          restaurant: '???',
          toilet: '???',
          bbq: '???',
          backHallway: '???',
          mainStairs: '???',
          geishaRoom: '???',
          hallway: '???',
          karaoke: '???',
          teaRoom: '???',
          taiko: '???',
          terrace: '???',
          backStairs: '???',
          houseBalcony: '???',
          exhibition: '???',
          lounge: '???',
          workOffice: '???',
          clearance: '???',
          peacefullTree: '???',
          contemplationGarden: '???',
          westGarden: '???',
          bridge: '???',
          gazeebo: '???',
          restBalcony: '???',
          northGarden: '???',
          eastGarden: '???',
          sandGarden: '???',
          sidePath: '???',
          sideStairs: '???',
          dragonStatue: '???',
          coveredWalkway: '???',
          drums: '???',
          geisha: '???',
          makeupRoom: '???',
          shrineBalcony: '???',
          officeBalcony: '???',
          geishaBalcony: '???',
          terraceBalcony: '???',
          restaurantStairs: '???',
          mezzanine: '???',
          shrine: '???',
          dragon: '???',
          office: '???',
          exhibitionRoom: '???',
          display: '???',
          vipClearance: '???',
          bar: '???',
          sushiBar: '???',
          coatCheck: '???',
          delivery: '???',
          walkIn: '???',
          bedroomCloset: '???',
          sideEntrance: '???'
        },
        themepark: {
          // EXT
          mainEntrance: '???',
          palms: '???',
          roboCircuit: '???',
          castleEntrance: '???',
          bumperCars: '???',
          guestInfo: '???',
          village: '???',
          sweetShop: '???',
          serviceEntrance: '???',
          teacups: '???',
          backAlley: '???',

          // 1F
          arcadeEntrance: '???',
          barrelRoom: '???',
          throneRoom: '???',
          maintenance: '???',
          dragonStairs: '???',
          blueRoom: '???',
          jointCorridor: '???',
          armory: '???',
          lab: '???',
          redCorridor: '???',
          gongRoom: '???',
          yellowCorridor: '???',
          tellers: '???',
          storage: '???',
          arcadeToilet: '???',
          lockerRoom: '???',

          // 2F
          upperArcade: '???',
          breakRoom: '???',
          initiationRoom: '???',
          controlRoom: '???',
          bunk: '???',
          dayCare: '???',
          // yellow corridor, but 2F /shrug
          waitingRoom: '???',
          cafeTerrace: '???',
          cashCorridor: '???',
          office: '???',
          cashStash: '???',
          cafeCorridor: '???',
          cafe: '???',
          officeShower: '???',
          officeVault: '???',

          // Roof
          roof: '???',

          // Stairs
          arcadeStairs: '???',
          yellowStairs: '???'
        },
        tower: {
          // EXT/Spawn
          northRoof: '???',
          northRoofNotShown: '???',
          southRoof: '???',
          southRoofNotShown: '???',
          roofAccess: '???',
          northRappel: '???',
          southRappel: '???',
          // 3F
          mezzanine: '???',
          ventilation: '???',
          // 2F
          centerAtrium: '???',
          infoBooth: '???',
          eastAtrium: '???',
          westAtrium: '???',
          eastBalcony: '???',
          westBalcony: '???',
          galleryMain: '???',
          mediaCenter: '???',
          galleryAnnex: '???',
          giftShop: '???',
          exhibitRoom: '???',
          lanternRoom: '???',
          elevator: '???',
          officesHallway: '???',
          exhibitHallway: '???',
          offices: '???',
          companyReception: '???',
          supplyRoom: '???',
          meetingRoom: '???',
          ceoOffice: '???',
          bathroom: '???',
          serverRoom: '???',
          // 2F to 1F Stairs
          northStairs: '???',
          westStairs: '???',
          eastStairs: '???',
          // 1F
          mainReception: '???',
          centerHallway: '???',
          teaRoom: '???',
          lounge: '???',
          bar: '???',
          kitchen: '???',
          restaurant: '???',
          birdRoom: '???',
          restaurantReception: '???',
          restaurantHallway: '???',
          barHallway: '???',
          westObservatory: '???',
          bonsaiRoom: '???',
          traditionalHall: '???',
          gameRoom: '???',
          eastObservatory: '???',
          fountain: '???',
          //Air Ducts:
          northAirDuct: '???',
          eastAirDuct: '???',
          westAirDuct: '???'
        },
        villa: {
          // South->North, West->East
          // Spawn
          spawnMainRoad: '???',
          spawnRuins: '???',
          spawnFountain: '???',
          // EXT
          ruins: '???',
          roundabout: '???',
          greenhouse: '???',
          frontEntrance: '???',
          roof: '???',
          terrace: '???',
          cryptTunnel: '???',
          crypt: '???',
          cryptEntrance: '???',
          garden: '???',
          driveway: '???',
          mainRoad: '???',
          balcony: '???',
          pergola: '???',
          stableYard: '???',
          skylightRoof: '???',
          bedroomRoof: '???',
          chapel: '???',
          garage: '???',
          fountain: '???',
          stable: '???',
          cellarTunnel: '???',
          sideRoad: '???',
          // 2F
          veranda: '???',
          classicalHall: '???',
          study: '???',
          gamesRoom: '???',
          aviatorRoom: '???',
          huntingVault: '???',
          landing: '???',
          trophyEntrance: '???',
          statuaryRoom: '???',
          trophyRoom: '???',
          masterBedroom: '???',
          astronomyRoom: '???',
          masterBathroom: '???',
          walkInCloset: '???',
          // 1F
          mainEntrance: '???',
          artStudio: '???',
          library: '???',
          mainHallway: '???',
          pianoRoom: '???',
          gallery: '???',
          toilet: '???',
          livingRoom: '???',
          bicycleStorage: '???',
          memorialRoom: '???',
          mudroom: '???',
          skylightHallway: '???',
          laundry: '???',
          backHallway: '???',
          diningRoom: '???',
          chinaRoom: '???',
          kitchen: '???',
          pantry: '???',
          // B
          tastingRoom: '???',
          archHallway: '???',
          artStorage: '???',
          oldOffice: '???',
          wineCellar: '???',
          // Stairs
          mainStairs: '???',
          redStairs: '???',
          backStairs: '???',
          pantryStairs: '???'
        },
        yacht: {
          spawnSubmarine: '???',
          spawnZodiak: '???',
          spawnSnowMobile: '???',
          mapsRoom: '???',
          cockpit: '???',
          cockpitHallway: '???',
          captainsOffice: '???',
          cockpitBalcony: '???',
          topDeckStairs: '???',
          helipadEntrance: '???',
          helipad: '???',
          spaDeck: '???',
          eastDeck: '???',
          westDeck: '???',
          frontDeck: '???',
          masterBedroom: '???',
          casino: '???',
          pokerRoom: '???',
          bathroom: '???',
          bedroomHallway: '???',
          casinoHallway: '???',
          globeHallway: '???',
          lounge: '???',
          cafeteria: '???',
          engine: '???',
          backEntrance: '???',
          rearDeck: '???',
          serverRoom: '???',
          engineStorage: '???',
          engineControl: '???',
          backStairs: '???',
          emergencyExit: '???',
          engineHallway: '???',
          frontStairs: '???',
          kitchen: '???',
          staffDormitory: '???',
          westBalcony: '???',
          eastBalcony: '???',
          kitchenHallway: '???',
          kitchenStairs: '???',
          kitchenPantry: '???',
          infirmary: '???',
          borealSubRoom: '???',
          cafeteriaHallway: '???',
          engineUtility: '???',
          submarine: '???',
          westGlacier: '???',
          eastHullBreach: '???',
          eastGlacier: '???',
          frozenRiver: '???',
          zodiac: '???',
          westHullBreach: '???',
          kingOfTheWorld: '???',
          roof: '???',
          anchorName: '???',
          aklarkSubEntrance: '???'
        }
      }
    };

  R6MLangTerms.registerLanguage(name, terms);

  // À  à  Â  â  Ç   ç  È  è  É  é  Ê  ê  Î  î  Ô  ô  Ù  ù  Û  û

  return  {
    name: name,
    terms: terms
  };
})(R6MLangTerms);
